version: 2.1

orbs:
  node: circleci/node@4.2.0

jobs:
  lint:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run linter
          command: npm run lint
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    executor: node/default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run tests
          command: npm run test:ci

workflows:
  lint-and-test:
    jobs:
      - lint
      - test:
          requires:
            - lint